# Generated by Django 4.0.2 on 2022-02-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricheck', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availableprimers',
            old_name='identifier',
            new_name='CHROM',
        ),
        migrations.RenameField(
            model_name='unavailableprimers',
            old_name='identifier',
            new_name='CHROM',
        ),
        migrations.AddField(
            model_name='availableprimers',
            name='POS',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availableprimers',
            name='Primer',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unavailableprimers',
            name='POS',
            field=models.CharField(default='no primer', max_length=200),
            preserve_default=False,
        ),
    ]
