# Generated by Django 3.1.7 on 2022-02-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricheck', '0002_rename_identifier_availableprimers_chrom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcf', models.FileField(upload_to='files/%Y/%m/%d')),
                ('bed', models.FileField(upload_to='files/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='availableprimers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unavailableprimers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
