# Generated by Django 4.0.2 on 2022-02-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricheck', '0003_auto_20220227_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableprimers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resultfiles',
            name='bed',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='resultfiles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resultfiles',
            name='vcf',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='unavailableprimers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
