# Generated by Django 4.0.2 on 2022-02-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricheck', '0004_alter_availableprimers_id_alter_resultfiles_bed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultFiles',
        ),
    ]
